### ISSUE TITLE
EX-百度网盘获取的直链，无法播放

### ISSUE THREAD

**Issue by V-MI** [cshuaimin/video-funnel#1]
使用说明的地址可以正常播放。
百度网盘的直链，失败了。
[

![0008](https://user-images.githubusercontent.com/14049291/34719289-357a83dc-f575-11e7-9432-e74e368449ae.jpg)

](url)

**Comment by cshuaimin** [comment]
我也遇到过 HTTP 400 Bad Request 的错误，好像是文件大于 4G 后直链就有问题了，否则的话你试试适当增大一点 `--piece-size` ，我的 1M 的时候不定时会出错，2M 就没事了。

**Comment by V-MI** [comment]
这样设置吗，还是错误
看样子好像没下载成功，说明中的地址，是可以看到下载的，百度网盘的  * Listening at port 8080 ...  之后就没动静了
都是几百兆的视频
![0009](https://user-images.githubusercontent.com/14049291/34720984-dc24294e-f57b-11e7-8a00-8bf6be13ab82.jpg)

**Comment by cshuaimin** [comment]
那就只剩最后一个办法，改 User-Agent ，目前还没有提供命令行选项，你熟悉 Python 的话去这一行暂时改一改，我尽快更新。
https://github.com/cshuaimin/video-funnel/blob/bb380339751b05c26a9d474e0cff5a1cecfb501b/video_funnel/__init__.py#L81
改成
```python
request.app['session'] = aiohttp.ClientSession(headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299'}) 
```

**Comment by V-MI** [comment]
改User-Agent😵还是400

**Comment by cshuaimin** [comment]
那实在抱歉:joy:玄学的百度网盘
有时间我再找找原因吧

**Comment by cshuaimin** [comment]
@V-MI 有可能是没有带 cookie 的原因，你可以尝试下加上浏览器的 cookie （`--with-cookies`参数）。对了，先更新一下 vf 。
