### ISSUE TITLE
也许应该使用encodeURI

### ISSUE THREAD

**Issue by Zxilly** [cshuaimin/video-funnel#10]
我好像没有看到解码部分

**Comment by cshuaimin** [comment]
我刚加上：https://github.com/cshuaimin/video-funnel/blob/0d69bd378afc28b4f7f71c0483da39f26c6fd314/video_funnel/index.html#L17
要是不 encode 下的话，URL 中含有参数的会和 block_size 一样成为 VF 的参数，而不是下载链接的一部分。
