### ISSUE TITLE
#9 的方法是否有效？

### ISSUE THREAD

**Issue by vcheckzen** [cshuaimin/video-funnel#11]
根据 <https://github.com/cshuaimin/video-funnel/issues/9> 的提示安装 `pycryptodome` 后，安装 `vf` 时还是要装 `pycrypto`，因为 `browsercookie` 依赖于它，我已向 `browsercookie`  项目发起 issue，提议转到 `pycryptodome`, 在此之前，作者是否可考虑弃用 `browsercookie`，转到类似模块。另找到了 `pycrypto` 的[预编译版本](http://www.voidspace.org.uk/python/pycrypto-2.6.1/)，不过仅提供到 python 3.4 之前。

**Comment by vcheckzen** [comment]
`pycookiecheat` 也依赖它，看来只能等两边慢慢转了

**Comment by cshuaimin** [comment]
获取 cookie 这个操作居然带来了这么大的麻烦，干脆砍掉算了:joy:

**Comment by vcheckzen** [comment]
我用 `-b 64M -p 512K` 缓冲 onedrive，前面 62M 跑满了宽带，20M 的网大概只要 30s，而最后 4M 感觉要 2-3min，严重拖慢了总体速度，有办法优化一下吗

**Comment by cshuaimin** [comment]
初步推测是因为大部分的 piece 都下载完了，只剩下少数几个仍在下载，这几个 piece 甚至只下载了一丁点，就一直拖着时间。或许需要更加详细的实验来确定。
解决方法是，在下载 block 的时候就尽量让所有的 piece 同步着，不要拉开大的差距，最后尽量一起完成。

**Comment by Zxilly** [comment]
@vcheckzen 如果你安装成功了，可以尝试使用py2exe来造福群众qwq

**Comment by vcheckzen** [comment]
> @vcheckzen 如果你安装成功了，可以尝试使用py2exe来造福群众qwq

做 exe 不一定所有系统都能跑起来，我在想是不是做个 docker 镜像容易点😀
