### ISSUE TITLE
百度网盘高速下载助手

### ISSUE THREAD

**Issue by gMan1990** [cshuaimin/video-funnel#13]
1. https://greasyfork.org/en/scripts/38661-百度网盘高速下载助手
Script has been deleted.
2. 如何限制 线程/连接 数？
3. 需要gcc ? 可以不编译吗？用Python不行吗？

----
4. `usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...`
infile支持http远程文件的，但是好像没多 线程/连接数 下载，速度慢。
aria2c有多连接数下载，所以ffmpeg和aria2c有木有结合的可能？或者看看还有其它什么方案吗？

**Comment by cshuaimin** [comment]
1. 推荐这个：https://github.com/syhyz1990/baiduyun
2. 连接数是由 `--block-size` 和 `--piece-size` 共同决定的，两者的商就是连接数。默认分别为 4M 和 1M，即 4 个连接。
3. 你是在 Windows 上安装吗？我没测试过，如果安装麻烦可以试试下面的方案。#9 #11
4. 来自 [V2EX](https://www.v2ex.com/t/420476#r_5175417) 的方案：
```sh
aria2c -x10 --stream-piece-selector=inorder
```

**Comment by gMan1990** [comment]
3. 我是在 https://cygwin.com/ 下安装的，提示要gcc编译，我以为这个工具可以类似 `python video-funnel.py` 或者 类似 `python -m video-funnel server` 这样执行 
4. 你的意思是使用aria2c下载到文件 file ，然后 `ffmpeg -re -i file out` 这样子吗？
    4.1 边下边ffmpeg, 这样子能大概率保证 ffmpeg 输出正常吗？
    4.2 我现在是这样子 `vf -u http 2>/dev/null &` 然后 `ffmpeg -re -i http://127.0.0.1:8080/ out`,勉强用着还行吧。

**Comment by cshuaimin** [comment]
3. 可能是用到的某个（获取浏览器 Cookie 的）库需要编译吧。
4. 下载到文件速度慢了读取端确实可能会读到垃圾，可以尝试管道或者 FIFO 之类的。

**Comment by gMan1990** [comment]
4.1 aria2c 好像不能输出到管道
4.2 是不是默认4线程太小了？我那样运行着 [oneindex](https://github.com/donwa/oneindex) 上的视频也不稳

**Comment by cshuaimin** [comment]
默认的我设的小，实际用的时候我都 8 个连接以上，比如 `-b32m -p2m` 这样，甚至 32、64 个地上:joy:

**Comment by gMan1990** [comment]
- https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-stream-piece-selector
    If default is given, aria2 selects piece so that it reduces the number of establishing connection. This is reasonable default behavior because establishing connection is an expensive operation
    下面的 size 如果很小 是不是意味着需要建立连接次数越多？(假设文件大小远远大于size)

- aria2c
    有--min-split-size参数，默认20M，这个调大调小是否和自身带宽有关联？比如
    - 1M带宽，感觉多少合适
    - 100M带宽，感觉多少合适

- video-funnel
    -b -p 是否也和带宽有关联？

**Comment by cshuaimin** [comment]
aria2c 的参数不清楚，我不用 aria2c。
关于 vf 的 -b -p 参数的作用，请参考 README。
