### ISSUE TITLE
在 GET 参数中传入 URL

### ISSUE THREAD

**Issue by Zxilly** [cshuaimin/video-funnel#6]
再开一个ffserver负载太大，而且浪费IO

**Comment by cshuaimin** [comment]
转为 webm 的目的是什么呢？

**Comment by Zxilly** [comment]
我傻了，我想表达的是根据Range分割为m3u8的TS流，我一直以为m3u8只能用webm

**Comment by Zxilly** [comment]
而且url最好能用GET方式传参，因为某些播放器会缓存同一个URL的Content-Length，然后会直接访问上一次的播放记录，还不能删除记录
如果用GET传参就好处理了，而且这样我就可以把它移植到路由器了

**Comment by Zxilly** [comment]
形如`192.168.1.1:8080/?url=http://xxx.com/mp4`这样的

**Comment by Zxilly** [comment]
如果能做好这个接口我可以写一个前端页面，用js来拼凑URL

**Comment by cshuaimin** [comment]
是有这个问题，播放器每次都问我是否要从上次的位置开始。。
但是用 GET 传参的话，要 encode URL，比较麻烦，之前的版本有这个功能的，后面给砍了:joy:

---
要是能有个前端界面那是最好了，晚上我就搞这个接口。

非常感谢！

**Comment by cshuaimin** [comment]
@Zxilly 现在的设计是这样的，你看看有没有什么问题？

首先将命令行参数中的 url 改为可选。

第一种传参的方法：`http://127.0.0.1:8080/http://example.com/movie.mp4`。模仿 web.archive.org 的做法，好处是不需要 encode URL，直接将两部分 URL 拼在一起就可以给播放器。

第二种：`http://127.0.0.1:8080/api?url=http%3A%2F%2Fexample.com%2Fmovie.mp4&block_size=4M&piece_size=1M`。好处是可以传入其他的参数，这样可以在 vf 的服务器启动后修改一些命令行参数。你的前端界面主要使用这个接口。

**Comment by Zxilly** [comment]
OK,我来写

**Comment by Zxilly** [comment]
`https://github.com/Zxilly/video_funnel_webui/blob/master/index.html`
写了一个，只有播放，本来可以有复制url的，但是我没弄出来，代码注释掉了，以后有空再说

**Comment by Zxilly** [comment]
没有做过滤，我不太清楚正则方面的东西

**Comment by cshuaimin** [comment]
嗯，挺好看的，谢谢大佬。

**Comment by cshuaimin** [comment]
要不要提个 PR 合并到 vf 中来呢？这样就可以通过 `http://127.0.0.1:8080/webui` 之类的来访问了。不过如果你想单独维护也行，一切随你。

**Comment by Zxilly** [comment]
我希望就是直接访问出现UI，这也是最符合直觉的方式了
但我不大会python，不知道怎么操作。。。

**Comment by Zxilly** [comment]
就是访问http://127.0.0.1:8080出现
如果说访问/webui的话功能就出现问题了，这个产生的是相对地址来着。。。

**Comment by cshuaimin** [comment]
这个地址是给播放器直接播放的啊，现在有两种方案：
1. 或许可以根据 `User-Agent` 是浏览器还是播放器来区分是返回视频流还是 webui？
2. 产生绝对地址？

**Comment by cshuaimin** [comment]
还有就是用个 video 标签来播放好呢还是现在这样直接打开？

**Comment by Zxilly** [comment]
访问ip出现这个UI，点击播放后直接在浏览器打开
要用播放器的话自己复制嘛
我回头加上生成的URL的显示

**Comment by Zxilly** [comment]
网页端的播放不做UI，我一开始考虑用video.js处理，后来觉得有点多此一举

**Comment by Zxilly** [comment]
你先把这个页面放进去，然后给我writeaccess，我以后可以慢慢搞定，你说的内嵌播放，太简陋就没意义了

**Comment by Zxilly** [comment]
如果vf启动时传入了URL就关闭web UI，web UI只在vf作为服务器启动时启用
这个逻辑应该没问题

**Comment by Zxilly** [comment]
加个—server参数233

**Comment by cshuaimin** [comment]
这样也行，那就相当于是有两个 UI，用 cli UI 的时候访问 `/` 返回视频流（为了清晰干脆在这种模式下关闭掉 HTTP API）；用 web UI 的时候访问 `/` 返回 html。

**Comment by cshuaimin** [comment]
https://github.com/cshuaimin/video-funnel/invitations
write access 是添加为 Collaborators 吗？邀请你了。

你来添加这个 html 文件吧，放在 video_funnel 文件夹下就行，若是以后可能会有其他的文件（css什么的），创建个 webui 之类的文件夹就行。

**Comment by Zxilly** [comment]
是的

**Comment by Zxilly** [comment]
加上了，合并分支吧

**Comment by Zxilly** [comment]
我不太清楚具体的修改，看代码好像还没有serve index.html?

**Comment by cshuaimin** [comment]
那等支持了合并还是合并后慢慢支持？

**Comment by cshuaimin** [comment]
算了还是先合并吧，那个 PR 的 commit 已经足够多了。
