### ISSUE TITLE
看了一下新的代码

### ISSUE THREAD

**Issue by Zxilly** [cshuaimin/video-funnel#7]
最好说明一下还要装python-devel和libffi-devel，用来编译pycrpto，这是browsercookie所依赖的

**Comment by cshuaimin** [comment]
抱歉，我没在 Windows 上测试过，安装这些是不是特别麻烦啊？要是不需要读取浏览器 cookie 的功能的话，那还是改成可选的好了，需要的用户自己去安装。

**Comment by Zxilly** [comment]
而且用setup限制库的版本会是一个好习惯，这能让程序更加鲁棒

**Comment by Zxilly** [comment]
> 抱歉，我没在 Windows 上测试过，安装这些是不是特别麻烦啊？要是不需要读取浏览器 cookie 的功能的话，那还是改成可选的好了，需要的用户自己去安装。

是的，需要安装VS

**Comment by cshuaimin** [comment]
> 而且用setup限制库的版本会是一个好习惯，这能让程序更加鲁棒

嗯，这次重构完会加上版本号的。

**Comment by vcheckzen** [comment]
> 抱歉，我没在 Windows 上测试过，安装这些是不是特别麻烦啊？要是不需要读取浏览器 cookie 的功能的话，那还是改成可选的好了，需要的用户自己去安装。

pycrpto 确实很难装，而且听说好几年不维护了
